import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"], // TODO: Add all the weights used within the projects.
});

// TODO: Update metadata object with relevant information.
export const metadata: Metadata = {
  title: "Hi, I am Abhay V Ashokan",
  description: "Generated by create next app",
  keywords: ["Software engineer", "React"],
  // twitter: { card: "summary_large_image", site: "@site", creator: "@creator", "images": "https://example.com/og.png" }
  // openGraph: {
  //   type: "website",
  //   url: "https://example.com",
  //   title: "My Website",
  //   description: "My Website Description",
  //   siteName: "My Website",
  //   images: [
  //     {
  //       url: "https://example.com/og.png",
  //     },
  //   ],
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
